---
output: html_document
---

```{r include=FALSE}

# packageの読み込み

library(nlme)
library(MASS)
library(ggplot2)
library(magrittr)
library(dplyr)
library(reshape2)
library(minpack.lm)
library(lattice)


# データの読み込み
adef<-read.csv(file="C:/Users/T.Hirano/Documents/【PJ】/Eisai_ADAS/ADEF_SMALL.csv")


# 同時点で記録のあるオブザベーションを削除
adef2 <- dplyr::distinct(adef, SUBJID, month, .keep_all=T)

# monthとCHGがNAであるオブザベーションを削除
adef3<-adef2[is.na(adef2$month)!=T & is.na(adef2$CHG)!=T,]

# 必要なデータだけ残す
adef3<-subset(adef3,select=c("SUBJID","month","CHG"))
```



元データのプロット


```{r echo=FALSE}


# プロット
ggplot(adef3, aes(x=month,y=CHG,group=SUBJID,colour=SUBJID))+
  geom_line()+guides(colour=F)+geom_hline(yintercept=0)+
  scale_y_continuous(limits = c(-30, 35))
```


```{r include=FALSE}

###############################################
### Non-linear Fitting by a kinetics model
###############################################

## モデル式 

# パラメータは正規分布
MDLFUNK <- function(k1, k2, A, xx) 70*(1-exp(-k1*xx))-A*(exp(-k1*xx)-exp(-k2*xx))-1/(k1-k2)*xx*exp(-k2*xx)



## 8例ごとで群を作成
adef3.id<-data.frame(SUBJID=unique(adef3$SUBJID))
adef3.id$NUM<-81:(81+nrow(adef3.id)-1)
adef3.id$GRP<-ceiling(adef3.id$NUM/8)
adef3.grp<-inner_join(adef3, adef3.id,by="SUBJID")
adef3.grp$SUBJID<-paste0(adef3.grp$GRP,"-",adef3.grp$SUBJID)

(adef3.grp <- groupedData(CHG ~ month | SUBJID,
                          data=adef3.grp))

## 時間
t<-sort(unique(adef3$month))

## パラメータ初期値  

# パラメータは正規分布
k1start<-.1
k2start<-.2
Astart<-10

# パラメータは対数正規分布
# kstart<-log(.003)
# k1start<-log(24.4)


## nls用に平均値のデータを作成
adef3.mean<-tapply(adef3.grp$CHG,adef3.grp$month,mean)
adef3.mean<-data.frame(month=as.numeric(names(adef3.mean)),CHG=adef3.mean)
row.names(adef3.mean)<-NULL

```



元データの平均値のプロット



```{r echo=FALSE}
## 平均値のデータをプロット
plot(adef3.mean,type="b",col="blue")
abline(h=0,v=0)
```



平均値に対するフィッティング

モデル式

ADAS = 

70 × (1 - exp(-k1 × month)) - A × (exp(-k1 × month) - exp(-k2 × month)) - 1/(k1 - k2) × month × exp(-k2 × month)



```{r echo=FALSE}
## nlsによるフィッティング（平均値）
(nls.out <- nls(CHG~MDLFUNK(k1, k2, A, month), 
                data=adef3.mean, start=list(k1=k1start, k2=k2start, A=Astart)))

summary(nls.out)
predict.c <- predict(nls.out)
plot(adef3.mean, ann=F,xlim=c(min(adef3.mean$month),max(adef3.mean$month)),
     ylim=c(min(adef3.mean$CHG),max(adef3.mean$CHG)));   par(new=T)
plot(adef3.mean$month, predict.c, type="l", xlim=c(min(adef3.mean$month),max(adef3.mean$month)),
     ylim=c(min(adef3.mean$CHG),max(adef3.mean$CHG)),
     col="blue")
abline(h=0,v=0)
```


NLMEによる解析


```{r include=FALSE}
## NLME
ADAS.nlme <- nlme(
  CHG ~ MDLFUNK(k1, k2, A, month),
  data=adef3.grp,
  fixed = k1 + k2 + A ~ 1,
  random = k1 + k2 + A ~ 1,
  start=coef(as.list(nls.out)),
  control=list(maxIter=1000,tolerance=.1,minScale=.0001),verbose = T)
```

```{r echo=FALSE}
summary(ADAS.nlme)
```


観測値 vs 予測値のプロット


```{r echo=FALSE}
## 観測値 vs 予測値のプロット
plot(ADAS.nlme,CHG~fitted(.),abline=c(0,1))
```



```{r include=FALSE}
## 個別データに対するフィッティングのプロット
ADAS.pred<-augPred(ADAS.nlme,level=0:1)
ADAS.pred$GRP<-as.numeric(substr(ADAS.pred$.groups,1,2))

NMBR<-unique(ADAS.pred$GRP)

# なぜかプロットされない
# for(i in 1:length(NMBR)){
#  print(NMBR[i])
#   plot(ADAS.pred[ADAS.pred$GRP==NMBR[i],])
# }
```


個別データに対するフィッティングのプロット


```{r echo=FALSE}
#やむなく書き下し
plot(ADAS.pred[ADAS.pred$GRP==NMBR[1],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[2],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[3],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[4],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[5],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[6],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[7],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[8],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[9],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[10],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[11],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[12],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[13],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[14],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[15],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[16],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[17],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[18],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[19],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[20],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[21],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[22],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[23],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[24],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[25],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[26],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[27],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[28],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[29],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[30],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[31],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[32],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[33],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[34],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[35],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[36],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[37],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[38],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[39],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[40],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[41],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[42],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[43],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[44],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[45],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[46],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[47],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[48],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[49],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[50],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[51],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[52],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[53],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[54],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[55],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[56],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[57],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[58],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[59],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[60],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[61],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[62],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[63],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[64],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[65],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[66],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[67],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[68],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[69],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[70],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[71],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[72],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[73],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[74],])
plot(ADAS.pred[ADAS.pred$GRP==NMBR[75],])



```